# Generated by Django 2.1.5 on 2019-02-25 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190225_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 6, 18, 59, 515300)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_received',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 6, 18, 59, 514968)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 6, 18, 59, 514950)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(upload_to='staticfiles'),
        ),
    ]
