# Generated by Django 2.1.5 on 2019-02-25 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190225_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 6, 43, 6, 715045)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_received',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 6, 43, 6, 714706)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 6, 43, 6, 714688)),
        ),
    ]
