# Generated by Django 2.1.5 on 2019-02-25 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190225_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 19, 13, 1, 508583)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_received',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 19, 13, 1, 508259)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 19, 13, 1, 508242)),
        ),
    ]
