# Generated by Django 2.1.7 on 2019-02-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_hashtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='hashtags',
            name='post',
        ),
        migrations.DeleteModel(
            name='Hashtags',
        ),
        migrations.AddField(
            model_name='post',
            name='Hashtags',
            field=models.ManyToManyField(to='api.Hashtag'),
        ),
    ]
