# Generated by Django 2.1.7 on 2019-02-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190226_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Hashtags',
            new_name='hashtags',
        ),
    ]
